apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-master
  labels:
    component: elasticsearch
    role: master
spec:
  ports:
  - name: "transport"
    port: 9300
    targetPort: 9300
  - name: "elasticsearch"
    port: 9200
    targetPort: 9200
  clusterIP: None
  selector:
    component: elasticsearch
    role: master
